const student=[
    {
name : 'Sabbir',
roll:'1',
className:'Ten',
age:17,
schoolname:'Rajshahi High School',
bn : 0,
en:70,
math:60,
s:80,
ss:70,
rel:85,
    },


    {
        name : 'Sifat',
        roll:'2',
        className:'Ten',
        age:18,
        schoolname:'Rajshahi High School',
        bn : 76,
        en:70,
        math:80,
        s:75,
        ss:40,
        rel:90,
            },

    {
        name : 'Naem',
        roll:'3',
        className:'Ten',
        age:16,
        schoolname:'Rajshahi High School',
        bn : 33,
        en:45,
        math:65,
        s:55,
        ss:75,
        rel:80,
            },
    {
        name : 'Yousuf',
        roll:'4',
        className:'Ten',
        age:19,
        schoolname:'Rajshahi High School',
        bn : 90,
        en:59,
        math:50,
        s:60,
        ss:69,
        rel:79,
            },
    {
        name : 'Nasrin',
        roll:'5',
        className:'Ten',
        age:19,
        schoolname:'Rajshahi High School',
        bn : 80,
        en:75,
        math:60,
        s:80,
        ss:40,
        rel:90,
            }


]